name: andi_challenge
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.21.6
  - matplotlib=3.3.4
  - scikit-learn=0.23.2
  - tensorflow=2.9.1
  - scipy=1.7.3
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - pip
  - pip:
      - andi-datasets==0.0.5
      - fbm==0.3.0
      - tqdm==4.55.2
